title = "Gitleaks config"

[allowlist]
pathRegexes = ["__pycache__/"]

[[rules]]
description = "Generic API Key"
regex = '''\b(api_key|token|secret)[\s=:]+["\']?[a-zA-Z0-9]{32,45}["\']?'''
tags = ["key", "generic"]
