version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: production-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    external: true  # <- wichtig! Gemeinsames Netzwerk mit anderen Compose-Dateien
