version: '3.8'

services:
  backend:
    build:
      context: ./backend
    mem_limit: 1g  # Setzt das Speicherlimit auf 1 GB
    cpu_shares: 1024  # Setzt das CPU-Sharing für den Container (Standardwert)
    env_file:
      - .env  # Lädt Umgebungsvariablen aus der .env-Datei
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 main:app  # Gunicorn konfigurieren
    ports:
      - "0.0.0.0:5000:5000"  # Ermöglicht den Zugriff auf Port 5000
    restart: always
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env  # Lädt Umgebungsvariablen aus der .env-Datei
    ports:
      - "0.0.0.0:3000:80"  # Ermöglicht den Zugriff auf Port 3000
    restart: always
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
