version: '3.8'

services:
  backend:
    build:
      context: ./backend
    mem_limit: 1g
    cpu_shares: 1024
    env_file:
      - .env
    command: gunicorn --workers 2 --timeout 180 --bind 0.0.0.0:5000 main:app
    ports:
      - "10.0.0.1:5000:5000"
    restart: always
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "0.0.0.0:3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    external: true  # <- jetzt identisch mit den anderen Dateien
