version: '3.9'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"  # Backend nur über VPN erreichbar
    restart: always
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Frontend nur über VPN erreichbar
    restart: always
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
