name: DevSecOps Light

on: [push, pull_request]

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 1. Gitleaks Secret Scan
    - name: Run Gitleaks Secret Scan
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_CONFIG: .gitleaks.toml

    # 2. Trivy SCA Scan
    - name: Trivy SCA Scan
      uses: aquasecurity/trivy-action@0.18.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        format: 'table'
        working-directory: 'backend'

    # 3. (A) Install requirements.txt for Syft
    - name: Install Python dependencies
      run: |
        python3 -m venv venv-backend
        source venv/bin/activate
        pip install -r backend/requirements.txt

    # 3. (B) SBOM aus requirements.txt (Ordner-Scan)
    - name: Generate SBOM from requirements
      uses: anchore/sbom-action@v0.15.0
      with:
        path: ./venv-backend
        format: spdx-json
        output-file: backend/sbom-from-requirements.spdx.json
        upload-artifact: false

    # Upload SBOM aus requirements.txt
    - name: Upload SBOM (requirements)
      uses: actions/upload-artifact@v4
      with:
        name: sbom-from-requirements
        path: backend/sbom-from-requirements.spdx.json

    # 4. Hadolint Dockerfile Check
    - name: Hadolint Dockerfile Lint
      uses: hadolint/hadolint-action@v3.0.0
      with:
        dockerfile: ./backend/Dockerfile
        failure-threshold: warning
        config: .hadolint.yml
        verbose: true

    - name: Output Hadolint logs if failed
      if: failure()
      run: echo "Hadolint failed. Please check the output above."

  build:
    needs: security_checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        cd backend
        docker build -t siadaia-backend .

    # SBOM aus Docker-Image erzeugen
    - name: Generate SBOM from Docker image
      uses: anchore/sbom-action@v0.15.0
      with:
        image: siadaia-backend
        format: spdx-json
        output-file: sbom-from-image.spdx.json
        upload-artifact: false

    - name: Upload SBOM (image)
      uses: actions/upload-artifact@v4
      with:
        name: sbom-from-image
        path: sbom-from-image.spdx.json
